spring:
  application:
    name: flowbridge
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5433/flowbridge
    username: flowbridge
    password: flowbridge
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flowbridge-workflow-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.flowbridge.kafka
        spring.json.value.default.type: com.flowbridge.kafka.WorkflowEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

flowbridge:
  kafka:
    workflow-events-topic: flowbridge.workflow.events
    consumer-group-id: flowbridge-workflow-consumer
