package com.flowbridge.enums;

public enum AuditEventType {
    REQUEST_RECEIVED,
    VALIDATION_PASSED,
    VALIDATION_FAILED,
    PAYLOAD_MAPPED,
    KAFKA_EVENT_QUEUED,
    KAFKA_EVENT_PUBLISHED,
    PROCESSING_STARTED,
    EXTERNAL_SYSTEM_CALL_STARTED,
    EXTERNAL_SYSTEM_CALL_SUCCEEDED,
    EXTERNAL_SYSTEM_CALL_FAILED,
    DUPLICATE_EVENT_SKIPPED,
    RETRY_REQUESTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED,
    INVALID_STATUS_TRANSITION
}
